// flow-typed signature: 985800495e671c03db8d4f15e879dcc6
// flow-typed version: <<STUB>>/@slate-editor/font-size-plugin_v^5.1.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@slate-editor/font-size-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@slate-editor/font-size-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@slate-editor/font-size-plugin/dist/FontSizeInput' {
  declare module.exports: any;
}

declare module '@slate-editor/font-size-plugin/dist/FontSizeKeyboardShortcut' {
  declare module.exports: any;
}

declare module '@slate-editor/font-size-plugin/dist/FontSizeMark' {
  declare module.exports: any;
}

declare module '@slate-editor/font-size-plugin/dist/FontSizeUtils' {
  declare module.exports: any;
}

declare module '@slate-editor/font-size-plugin/dist/index' {
  declare module.exports: any;
}

declare module '@slate-editor/font-size-plugin/dist/ValidatePluginOptions' {
  declare module.exports: any;
}

// Filename aliases
declare module '@slate-editor/font-size-plugin/dist/FontSizeInput.js' {
  declare module.exports: $Exports<'@slate-editor/font-size-plugin/dist/FontSizeInput'>;
}
declare module '@slate-editor/font-size-plugin/dist/FontSizeKeyboardShortcut.js' {
  declare module.exports: $Exports<'@slate-editor/font-size-plugin/dist/FontSizeKeyboardShortcut'>;
}
declare module '@slate-editor/font-size-plugin/dist/FontSizeMark.js' {
  declare module.exports: $Exports<'@slate-editor/font-size-plugin/dist/FontSizeMark'>;
}
declare module '@slate-editor/font-size-plugin/dist/FontSizeUtils.js' {
  declare module.exports: $Exports<'@slate-editor/font-size-plugin/dist/FontSizeUtils'>;
}
declare module '@slate-editor/font-size-plugin/dist/index.js' {
  declare module.exports: $Exports<'@slate-editor/font-size-plugin/dist/index'>;
}
declare module '@slate-editor/font-size-plugin/dist/ValidatePluginOptions.js' {
  declare module.exports: $Exports<'@slate-editor/font-size-plugin/dist/ValidatePluginOptions'>;
}
