// flow-typed signature: 755ca7da34f8a889db45480e48e3a00e
// flow-typed version: <<STUB>>/object.omit_v^3.0.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object.omit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object.omit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'object.omit/index' {
  declare module.exports: $Exports<'object.omit'>;
}
declare module 'object.omit/index.js' {
  declare module.exports: $Exports<'object.omit'>;
}
