// flow-typed signature: a771c7582a6c0385d0754e4c8fae54c4
// flow-typed version: <<STUB>>/react-google-login_v^5.0.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-login'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-google-login' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-google-login/__test__/google-login-dist.test' {
  declare module.exports: any;
}

declare module 'react-google-login/__test__/google-login.test' {
  declare module.exports: any;
}

declare module 'react-google-login/__test__/google-logout-dist.test' {
  declare module.exports: any;
}

declare module 'react-google-login/__test__/google-logout.test' {
  declare module.exports: any;
}

declare module 'react-google-login/demo/app' {
  declare module.exports: any;
}

declare module 'react-google-login/demo/index' {
  declare module.exports: any;
}

declare module 'react-google-login/dist/google-login' {
  declare module.exports: any;
}

declare module 'react-google-login/src/button-content' {
  declare module.exports: any;
}

declare module 'react-google-login/src/google-login' {
  declare module.exports: any;
}

declare module 'react-google-login/src/google-logout' {
  declare module.exports: any;
}

declare module 'react-google-login/src/icon' {
  declare module.exports: any;
}

declare module 'react-google-login/src/index' {
  declare module.exports: any;
}

declare module 'react-google-login/webpack/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'react-google-login/webpack/webpack.config.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-google-login/__test__/google-login-dist.test.js' {
  declare module.exports: $Exports<'react-google-login/__test__/google-login-dist.test'>;
}
declare module 'react-google-login/__test__/google-login.test.js' {
  declare module.exports: $Exports<'react-google-login/__test__/google-login.test'>;
}
declare module 'react-google-login/__test__/google-logout-dist.test.js' {
  declare module.exports: $Exports<'react-google-login/__test__/google-logout-dist.test'>;
}
declare module 'react-google-login/__test__/google-logout.test.js' {
  declare module.exports: $Exports<'react-google-login/__test__/google-logout.test'>;
}
declare module 'react-google-login/demo/app.js' {
  declare module.exports: $Exports<'react-google-login/demo/app'>;
}
declare module 'react-google-login/demo/index.js' {
  declare module.exports: $Exports<'react-google-login/demo/index'>;
}
declare module 'react-google-login/dist/google-login.js' {
  declare module.exports: $Exports<'react-google-login/dist/google-login'>;
}
declare module 'react-google-login/src/button-content.js' {
  declare module.exports: $Exports<'react-google-login/src/button-content'>;
}
declare module 'react-google-login/src/google-login.js' {
  declare module.exports: $Exports<'react-google-login/src/google-login'>;
}
declare module 'react-google-login/src/google-logout.js' {
  declare module.exports: $Exports<'react-google-login/src/google-logout'>;
}
declare module 'react-google-login/src/icon.js' {
  declare module.exports: $Exports<'react-google-login/src/icon'>;
}
declare module 'react-google-login/src/index.js' {
  declare module.exports: $Exports<'react-google-login/src/index'>;
}
declare module 'react-google-login/webpack/webpack.config.dev.js' {
  declare module.exports: $Exports<'react-google-login/webpack/webpack.config.dev'>;
}
declare module 'react-google-login/webpack/webpack.config.prod.js' {
  declare module.exports: $Exports<'react-google-login/webpack/webpack.config.prod'>;
}
