// flow-typed signature: 0cac9ae174ba1ab6a7d92a874ef7f055
// flow-typed version: <<STUB>>/react-sortly_v^1.5.5/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sortly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sortly' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sortly/dist/Sortly' {
  declare module.exports: any;
}

declare module 'react-sortly/lib/index' {
  declare module.exports: any;
}

declare module 'react-sortly/lib/Item' {
  declare module.exports: any;
}

declare module 'react-sortly/lib/Sortly' {
  declare module.exports: any;
}

declare module 'react-sortly/lib/utils' {
  declare module.exports: any;
}

declare module 'react-sortly/test/utils.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sortly/dist/Sortly.js' {
  declare module.exports: $Exports<'react-sortly/dist/Sortly'>;
}
declare module 'react-sortly/lib/index.js' {
  declare module.exports: $Exports<'react-sortly/lib/index'>;
}
declare module 'react-sortly/lib/Item.js' {
  declare module.exports: $Exports<'react-sortly/lib/Item'>;
}
declare module 'react-sortly/lib/Sortly.js' {
  declare module.exports: $Exports<'react-sortly/lib/Sortly'>;
}
declare module 'react-sortly/lib/utils.js' {
  declare module.exports: $Exports<'react-sortly/lib/utils'>;
}
declare module 'react-sortly/test/utils.spec.js' {
  declare module.exports: $Exports<'react-sortly/test/utils.spec'>;
}
