// flow-typed signature: 617f56e50272981fdf617160e6305417
// flow-typed version: <<STUB>>/stylis-plugin-extra-scope_v^0.1.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylis-plugin-extra-scope'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylis-plugin-extra-scope' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylis-plugin-extra-scope/dist/stylis-plugin-extra-scope.es' {
  declare module.exports: any;
}

declare module 'stylis-plugin-extra-scope/dist/stylis-plugin-extra-scope' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylis-plugin-extra-scope/dist/stylis-plugin-extra-scope.es.js' {
  declare module.exports: $Exports<'stylis-plugin-extra-scope/dist/stylis-plugin-extra-scope.es'>;
}
declare module 'stylis-plugin-extra-scope/dist/stylis-plugin-extra-scope.js' {
  declare module.exports: $Exports<'stylis-plugin-extra-scope/dist/stylis-plugin-extra-scope'>;
}
