export default [
    {
        expanded: true,
        id: 'element_02',
        itemPath: [],
        path: [],
        tag: 'CMS variables',
    },
    { expanded: true, id: 'element_01', itemPath: [], path: [], tag: 'html' },
    {
        id: 'element_0',
        itemPath: ['element_01'],
        path: ['element_01'],
        tag: 'head',
    },
    {
        expanded: true,
        id: 'element_1',
        itemPath: ['element_01'],
        path: ['element_01'],
        tag: 'body',
    },
    {
        id: 'element_2',
        itemPath: ['element_01', 'element_1'],
        path: ['element_01', 'element_1'],
        tag: 'websiterMenu',
    },
    {
        childrenTo: 'overflowIcon',
        forChildren: true,
        forModule: 'element_2',
        id: 'element_2_childrenTo_overflowIcon',
        isChildren: false,
        path: ['element_01', 'element_1', 'element_2'],
        sourcePlugin: '',
        tag: 'Overflow icon',
        text: false,
    },
    {
        childrenTo: 'expandIcon',
        forChildren: true,
        forModule: 'element_2',
        id: 'element_2_childrenTo_expandIcon',
        isChildren: false,
        path: ['element_01', 'element_1', 'element_2'],
        sourcePlugin: '',
        tag: 'Expand icon',
        text: false,
    },
    { expanded: true, id: 'trash', itemPath: [], path: [], tag: 'Trash' },
]
