export default [
    {
        id: 'element_0',
        tag: 'Main element',
        itemPath: [],
        expanded: true,
        path: [],
    },
    {
        id: 'element_1',
        tag: 'websiterMenu',
        isPropagatingItem: false,
        textMode: 'text',
        text: false,
        isChildren: false,
        isCMSVariable: false,
        isElementFromCMSVariable: false,
        itemPath: ['element_0'],
        expanded: true,
        path: ['element_0'],
    },
    {
        id: 'element_1_childrenTo_overflowIcon',
        childrenTo: 'overflowIcon',
        forModule: 'element_1',
        sourcePlugin: '5ed4bd0d7587fb34e9634305',
        text: false,
        isChildren: false,
        forChildren: true,
        tag: 'Overflow icon',
        itemPath: ['element_0', 'element_1'],
        path: ['element_0', 'element_1'],
    },
    {
        id: 'element_1_childrenTo_expandIcon',
        childrenTo: 'expandIcon',
        forModule: 'element_1',
        sourcePlugin: '5ed4bd0d7587fb34e9634305',
        text: false,
        isChildren: false,
        forChildren: true,
        tag: 'Expand icon',
        itemPath: ['element_0', 'element_1'],
        path: ['element_0', 'element_1'],
    },
]
