export default [
    {
        expanded: true,
        id: 'element_0',
        itemPath: [],
        path: [],
        tag: 'Main element',
    },
    {
        expanded: true,
        id: 'element_1',
        isCMSVariable: false,
        isChildren: false,
        isElementFromCMSVariable: false,
        isPropagatingItem: false,
        itemPath: ['element_0'],
        path: ['element_0'],
        tag: 'Lola',
        text: false,
        textMode: 'text',
    },
    {
        childrenTo: 'element_1',
        expanded: true,
        forChildren: true,
        forPlugin: '5ed4dd3058cd1e16badab1de',
        id: 'element_1_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_1',
        isChildren: false,
        itemPath: ['element_0', 'element_1'],
        path: ['element_0', 'element_1'],
        sourcePlugin: '5ed4f64935b6740e8fd6b30e',
        tag: 'Children for TestChild',
        text: false,
    },
    {
        expanded: true,
        id: 'element_2',
        isCMSVariable: false,
        isChildren: false,
        isElementFromCMSVariable: false,
        isPropagatingItem: false,
        itemPath: [
            'element_0',
            'element_1',
            'element_1_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_1',
        ],
        path: [
            'element_0',
            'element_1',
            'element_1_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_1',
        ],
        tag: 'div',
        text: false,
        textMode: 'text',
    },
    {
        expanded: true,
        id: 'element_4',
        isCMSVariable: false,
        isChildren: false,
        isElementFromCMSVariable: false,
        isPropagatingItem: false,
        itemPath: [
            'element_0',
            'element_1',
            'element_1_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_1',
            'element_2',
        ],
        path: [
            'element_0',
            'element_1',
            'element_1_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_1',
            'element_2',
        ],
        tag: 'websiterMenu',
        text: false,
        textMode: 'text',
    },
    {
        childrenTo: 'overflowIcon',
        forChildren: true,
        forModule: 'element_4',
        id: 'element_4_childrenTo_overflowIcon',
        isChildren: false,
        itemPath: [
            'element_0',
            'element_1',
            'element_1_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_1',
            'element_2',
            'element_4',
        ],
        path: [
            'element_0',
            'element_1',
            'element_1_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_1',
            'element_2',
            'element_4',
        ],
        sourcePlugin: '5ed4f64935b6740e8fd6b30e',
        tag: 'Overflow icon',
        text: false,
    },
    {
        childrenTo: 'expandIcon',
        forChildren: true,
        forModule: 'element_4',
        id: 'element_4_childrenTo_expandIcon',
        isChildren: false,
        itemPath: [
            'element_0',
            'element_1',
            'element_1_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_1',
            'element_2',
            'element_4',
        ],
        path: [
            'element_0',
            'element_1',
            'element_1_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_1',
            'element_2',
            'element_4',
        ],
        sourcePlugin: '5ed4f64935b6740e8fd6b30e',
        tag: 'Expand icon',
        text: false,
    },
    {
        childrenTo: 'element_2',
        expanded: true,
        forChildren: true,
        forPlugin: '5ed4dd3058cd1e16badab1de',
        id: 'element_1_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_2',
        isChildren: false,
        itemPath: ['element_0', 'element_1'],
        path: ['element_0', 'element_1'],
        sourcePlugin: '5ed4f64935b6740e8fd6b30e',
        tag: 'Children for TestChild2',
        text: false,
    },
    {
        id: 'element_3',
        isCMSVariable: false,
        isChildren: false,
        isElementFromCMSVariable: false,
        isPropagatingItem: false,
        itemPath: [
            'element_0',
            'element_1',
            'element_1_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_2',
        ],
        path: [
            'element_0',
            'element_1',
            'element_1_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_2',
        ],
        tag: 'div',
        text: false,
        textMode: 'text',
    },
]
