export default {
    userObject: {
        websites: [
            { id: '5e95a4375da9c91a2716debc' },
            { id: '5ece8684273f8145e5f04439' },
        ],
        settings: {
            websites: {
                '5e95a4375da9c91a2716debc': {
                    currentPageFSBId: '5eab7d3c2548796bd4100df0',
                    currentPageId: '5eab7d3c2548796bd4100df0',
                    currentTemplateId: '5ea5a4a3a49095490f9d88b9',
                    currentFileId: 'file_20',
                    currentPluginId: '5eb198888304356a8988ea63',
                },
                '5ece8684273f8145e5f04439': {
                    currentPluginId: '5ed4dd3058cd1e16badab1de',
                    currentTemplateId: '5ed4dde158cd1e16badab1e0',
                    currentPageFSBId: '5ed188c8d2145f2291cbf67b',
                    currentPageId: '5ed188c8d2145f2291cbf67b',
                },
            },
            currentWebsite: '5ece8684273f8145e5f04439',
            barSizes: { height: 434, width: 500, width2: 452, width3: 414 },
        },
        logoutAllDate: 1586864607351,
        _id: '5e95a4375da9c91a2716debb',
        userid: '7085000',
        platformId: 'github',
        accountInfo: {
            displayName: null,
            photos: [
                {
                    value:
                        'https://avatars0.githubusercontent.com/u/7085000?v=4',
                },
            ],
        },
        __v: 832,
        __patch__: { '1': [{ id: '5ece8684273f8145e5f04439' }], _t: 'a' },
    },
    websites: [
        { id: '5e95a4375da9c91a2716debc' },
        { id: '5ece8684273f8145e5f04439' },
    ],
    currentWebsiteItem: { id: '5ece8684273f8145e5f04439' },
    currentWebsiteId: '5ece8684273f8145e5f04439',
    currentWebsiteObject: {
        sharing: [
            {
                userId: '5e95a4375da9c91a2716debb',
                rights: ['owner', 'admin', 'developer', 'content'],
                accountInfo: {
                    displayName: null,
                    photos: [
                        {
                            value:
                                'https://avatars0.githubusercontent.com/u/7085000?v=4',
                        },
                    ],
                },
            },
        ],
        filesStructure: [],
        pagesStructure: [
            {
                id: '5ece8684273f8145e5f0443a',
                name: 'Global website settings',
                url: '__general__settings__',
                hidden: true,
                path: [],
                published: true,
                generalSettings: true,
                template: 'Global website settings',
                relUrl: '/__general__settings__',
                homepage: false,
                isHomePage: true,
            },
        ],
        pluginsStructure: [
            {
                id: '5ed4dd3058cd1e16badab1de',
                path: [],
                name: 'Lola',
                published: true,
            },
        ],
        templatesStructure: [
            {
                id: '5ece8684273f8145e5f0443b',
                name: 'Global website settings',
                url: '__general__settings__',
                hidden: true,
                path: [],
                published: true,
                generalSettings: true,
            },
            {
                id: '5ed4dde158cd1e16badab1e0',
                path: [],
                name: 'New template',
                published: false,
            },
        ],
        _id: '5ece8684273f8145e5f04439',
        name: 'New website',
        domain: 'new-website-13',
        user: '5e95a4375da9c91a2716debb',
        storage: 0,
        __v: 36,
        __patch__: {
            sharing: {
                '0': [
                    {
                        userId: '5e95a4375da9c91a2716debb',
                        rights: ['owner', 'admin', 'developer', 'content'],
                        accountInfo: {
                            displayName: null,
                            photos: [
                                {
                                    value:
                                        'https://avatars0.githubusercontent.com/u/7085000?v=4',
                                },
                            ],
                        },
                    },
                ],
                _t: 'a',
                _0: [
                    {
                        userId: '5e95a4375da9c91a2716debb',
                        rights: ['owner', 'admin', 'developer', 'content'],
                        accountInfo: {
                            displayName: null,
                            photos: [
                                {
                                    value:
                                        'https://avatars0.githubusercontent.com/u/7085000?v=4',
                                },
                            ],
                        },
                    },
                    0,
                    0,
                ],
            },
            pluginsStructure: {
                _t: 'a',
                _1: [
                    {
                        id: '5ed4f59e35b6740e8fd6b30d',
                        path: [],
                        name: 'New plugin',
                        published: true,
                    },
                    0,
                    0,
                ],
            },
        },
    },
    pagesStructure: [
        {
            id: '5ece8684273f8145e5f0443a',
            name: 'Global website settings',
            url: '__general__settings__',
            hidden: true,
            path: [],
            published: true,
            generalSettings: true,
            template: 'Global website settings',
            relUrl: '/__general__settings__',
            homepage: false,
            isHomePage: true,
        },
    ],
    templatesStructure: [
        {
            id: '5ece8684273f8145e5f0443b',
            name: 'Global website settings',
            url: '__general__settings__',
            hidden: true,
            path: [],
            published: true,
            generalSettings: true,
        },
        {
            id: '5ed4dde158cd1e16badab1e0',
            path: [],
            name: 'New template',
            published: false,
        },
    ],
    pluginsStructure: [
        {
            id: '5ed4dd3058cd1e16badab1de',
            path: [],
            name: 'Lola',
            published: true,
        },
    ],
    filesStructure: [],
    currentPageId: '5ed188c8d2145f2291cbf67b',
    currentPageFSBId: '5ed188c8d2145f2291cbf67b',
    currentTemplateId: '5ed4dde158cd1e16badab1e0',
    currentPluginId: '5ed4dd3058cd1e16badab1de',
    currentTemplateItem: {
        id: '5ed4dde158cd1e16badab1e0',
        path: [],
        name: 'New template',
        published: false,
    },
    currentPluginItem: {
        id: '5ed4dd3058cd1e16badab1de',
        path: [],
        name: 'Lola',
        published: true,
    },
    currentTemplateObject: {
        draft: {
            currentId: 3,
            structure: [
                {
                    id: 'element_02',
                    path: [],
                    tag: 'CMS variables',
                    itemPath: [],
                },
                {
                    id: 'element_01',
                    path: [],
                    tag: 'html',
                    itemPath: [],
                    expanded: true,
                },
                {
                    id: 'element_0',
                    path: ['element_01'],
                    tag: 'head',
                    itemPath: ['element_01'],
                },
                {
                    id: 'element_1',
                    path: ['element_01'],
                    tag: 'body',
                    itemPath: ['element_01'],
                    expanded: true,
                },
                {
                    id: 'element_2',
                    path: ['element_01', 'element_1'],
                    tag: 'Lola',
                    itemPath: ['element_01', 'element_1'],
                    expanded: true,
                },
                {
                    id:
                        'element_2_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_1',
                    childrenTo: 'element_1',
                    forPlugin: '5ed4dd3058cd1e16badab1de',
                    sourcePlugin: '',
                    text: false,
                    isChildren: false,
                    forChildren: true,
                    tag: 'Children for TestChild',
                    itemPath: ['element_01', 'element_1', 'element_2'],
                    path: ['element_01', 'element_1', 'element_2'],
                },
            ],
            values: {
                element_02: { properties: {}, style: '' },
                element_01: { properties: {}, style: '' },
                element_0: { properties: {}, style: '' },
                element_1: { properties: {}, style: '' },
                element_2: {
                    properties: {},
                    style:
                        'height: 100px;width: 100px;left: 200px;top: 100px;z-index: 0;background: rgba(100, 0, 80);',
                },
            },
            connectedResources: [{ name: 'Lola', type: 'plugin' }],
            currentBox: 'element_2',
        },
        present: {
            currentId: 3,
            structure: [
                {
                    id: 'element_02',
                    tag: 'CMS variables',
                    itemPath: [],
                    path: [],
                },
                {
                    id: 'element_01',
                    tag: 'html',
                    itemPath: [],
                    expanded: true,
                    path: [],
                },
                {
                    id: 'element_0',
                    tag: 'head',
                    itemPath: ['element_01'],
                    path: ['element_01'],
                },
                {
                    id: 'element_1',
                    tag: 'body',
                    itemPath: ['element_01'],
                    expanded: true,
                    path: ['element_01'],
                },
                {
                    id: 'element_2',
                    tag: 'Lola',
                    itemPath: ['element_01', 'element_1'],
                    expanded: true,
                    path: ['element_01', 'element_1'],
                },
                {
                    id:
                        'element_2_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_1',
                    childrenTo: 'element_1',
                    forPlugin: '5ed4dd3058cd1e16badab1de',
                    sourcePlugin: '',
                    path: ['element_01', 'element_1', 'element_2'],
                    text: false,
                    isChildren: false,
                    forChildren: true,
                    tag: 'Children for New children',
                },
            ],
            values: {
                element_02: { properties: {}, style: '' },
                element_01: { properties: {}, style: '' },
                element_0: { properties: {}, style: '' },
                element_1: { properties: {}, style: '' },
                element_2: {
                    properties: {},
                    style:
                        'height: 100px;width: 100px;left: 200px;top: 100px;z-index: 0;background: rgba(100, 0, 80);',
                },
            },
            connectedResources: [{ name: 'Lola', type: 'plugin' }],
            currentBox: 'element_2',
        },
        future: [],
        past: [],
        __v: 1,
        _id: '5ed4dde158cd1e16badab1e0',
    },
    currentPluginObject: {
        draft: {
            currentId: 1,
            structure: [{ id: 'element_0', path: [], tag: 'Main element' }],
            values: { element_0: { properties: {} } },
            connectedResources: [],
        },
        present: {
            currentId: 2,
            structure: [
                {
                    id: 'element_0',
                    tag: 'Main element',
                    itemPath: [],
                    expanded: true,
                    path: [],
                },
                {
                    id: 'element_1',
                    tag: 'TestChild',
                    isPropagatingItem: false,
                    textMode: 'text',
                    text: false,
                    isChildren: true,
                    isCMSVariable: false,
                    isElementFromCMSVariable: false,
                    itemPath: ['element_0'],
                    path: ['element_0'],
                },
            ],
            values: {
                element_0: { properties: {} },
                element_1: {
                    textContent: '',
                    properties: {},
                    propertiesString: '',
                    CMSVariableType: 'text',
                    CMSVariableSystemName: 'newCmsVariable',
                    CMSVariableDescription: 'New CMS variable description',
                    CMSVariableDefaultValue: 'New CMS variable default value',
                },
            },
            connectedResources: [],
            currentBox: 'element_1',
        },
        future: [],
        past: [],
        __v: 0,
        _id: '5ed4dd3058cd1e16badab1de',
    },
    currentTemplateDraft: {
        currentId: 3,
        structure: [
            { id: 'element_02', tag: 'CMS variables', itemPath: [], path: [] },
            {
                id: 'element_01',
                tag: 'html',
                itemPath: [],
                expanded: true,
                path: [],
            },
            {
                id: 'element_0',
                tag: 'head',
                itemPath: ['element_01'],
                path: ['element_01'],
            },
            {
                id: 'element_1',
                tag: 'body',
                itemPath: ['element_01'],
                expanded: true,
                path: ['element_01'],
            },
            {
                id: 'element_2',
                tag: 'Lola',
                itemPath: ['element_01', 'element_1'],
                expanded: true,
                path: ['element_01', 'element_1'],
            },
            {
                id:
                    'element_2_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_1',
                childrenTo: 'element_1',
                forPlugin: '5ed4dd3058cd1e16badab1de',
                sourcePlugin: '',
                path: ['element_01', 'element_1', 'element_2'],
                text: false,
                isChildren: false,
                forChildren: true,
                tag: 'Children for New children',
            },
        ],
        values: {
            element_02: { properties: {}, style: '' },
            element_01: { properties: {}, style: '' },
            element_0: { properties: {}, style: '' },
            element_1: { properties: {}, style: '' },
            element_2: {
                properties: {},
                style:
                    'height: 100px;width: 100px;left: 200px;top: 100px;z-index: 0;background: rgba(100, 0, 80);',
            },
        },
        connectedResources: [{ name: 'Lola', type: 'plugin' }],
        currentBox: 'element_2',
    },
    currentPluginDraft: {
        currentId: 2,
        structure: [
            {
                id: 'element_0',
                tag: 'Main element',
                itemPath: [],
                expanded: true,
                path: [],
            },
            {
                id: 'element_1',
                tag: 'TestChild',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: true,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                itemPath: ['element_0'],
                path: ['element_0'],
            },
        ],
        values: {
            element_0: { properties: {} },
            element_1: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'text',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
            },
        },
        connectedResources: [],
        currentBox: 'element_1',
    },
    globalSettingsPageId: '5ece8684273f8145e5f0443a',
    globalSettingsPageObject: {
        draft: { structure: [], values: {}, connectedResources: [] },
        present: {},
        future: [],
        past: [],
        __v: 0,
        _id: '5ece8684273f8145e5f0443a',
    },
    globalSettingsPageDraft: {
        structure: [],
        values: {},
        connectedResources: [],
    },
    globalSettingsTemplateId: '5ece8684273f8145e5f0443b',
    globalSettingsTemplateDraft: {
        currentId: 3,
        structure: [{ id: 'element_02', path: [], tag: 'CMS variables' }],
        values: { element_02: { properties: {}, style: '' } },
        connectedResources: [],
    },
    pageTemplateName: '',
    pageTemplateId: '',
    pageTemplateFSBName: '',
    pageTemplateFSBId: '',
    resourcesObjects: {
        '5e95a4375da9c91a2716debb': {
            websites: [
                { id: '5e95a4375da9c91a2716debc' },
                { id: '5ece8684273f8145e5f04439' },
            ],
            settings: {
                websites: {
                    '5e95a4375da9c91a2716debc': {
                        currentPageFSBId: '5eab7d3c2548796bd4100df0',
                        currentPageId: '5eab7d3c2548796bd4100df0',
                        currentTemplateId: '5ea5a4a3a49095490f9d88b9',
                        currentFileId: 'file_20',
                        currentPluginId: '5eb198888304356a8988ea63',
                    },
                    '5ece8684273f8145e5f04439': {
                        currentPluginId: '5ed4dd3058cd1e16badab1de',
                        currentTemplateId: '5ed4dde158cd1e16badab1e0',
                        currentPageFSBId: '5ed188c8d2145f2291cbf67b',
                        currentPageId: '5ed188c8d2145f2291cbf67b',
                    },
                },
                currentWebsite: '5ece8684273f8145e5f04439',
                barSizes: { height: 434, width: 500, width2: 452, width3: 414 },
            },
            logoutAllDate: 1586864607351,
            _id: '5e95a4375da9c91a2716debb',
            userid: '7085000',
            platformId: 'github',
            accountInfo: {
                displayName: null,
                photos: [
                    {
                        value:
                            'https://avatars0.githubusercontent.com/u/7085000?v=4',
                    },
                ],
            },
            __v: 832,
            __patch__: { '1': [{ id: '5ece8684273f8145e5f04439' }], _t: 'a' },
        },
        '5e95a4375da9c91a2716debc': {
            sharing: [
                {
                    userId: '5e95a4375da9c91a2716debb',
                    rights: ['owner', 'admin', 'content', 'developer'],
                    accountInfo: {
                        displayName: null,
                        photos: [
                            {
                                value:
                                    'https://avatars0.githubusercontent.com/u/7085000?v=4',
                            },
                        ],
                    },
                },
            ],
            filesStructure: [
                {
                    id: 'file_0',
                    path: [],
                    size: 0,
                    name: 'New file.css',
                    serverName: '5e95a4375da9c91a2716debc/New_file.css',
                    type: 'text/css',
                    url:
                        'https://websiter.s3.amazonaws.com/5e95a4375da9c91a2716debc/New_file.css',
                    v: 1,
                    resolution: { width: 'unknown', height: 'unknown' },
                    modifiedDate: 1587825292274,
                    relUrl: '/New file.css',
                },
                {
                    id: 'file_17',
                    path: [],
                    size: 113,
                    name: 'style.css',
                    serverName: '5e95a4375da9c91a2716debc/New_file.css_2',
                    type: 'text/css',
                    url:
                        'https://websiter.s3.amazonaws.com/5e95a4375da9c91a2716debc/New_file.css_2',
                    v: 4,
                    resolution: { width: 'unknown', height: 'unknown' },
                    modifiedDate: 1589508659712,
                    createdDate: 1589472453046,
                    relUrl: '/style.css',
                    editorMode: 'css',
                },
                {
                    id: 'file_6',
                    path: [],
                    size: 135030,
                    name: 'SampleImage.png',
                    serverName: '5e95a4375da9c91a2716debc/SampleImage.png',
                    type: 'image/png',
                    url:
                        'https://websiter.s3.amazonaws.com/5e95a4375da9c91a2716debc/SampleImage.png',
                    v: 5,
                    resolution: { width: 490, height: 179 },
                    modifiedDate: 1588678994464,
                    relUrl: '/SampleImage.png',
                    editorMode: 'css',
                },
                {
                    id: 'file_18',
                    path: [],
                    size: 54083,
                    name: 'ABOUT-US-_IMAGE.jpg',
                    serverName: '5e95a4375da9c91a2716debc/ABOUT-US-_IMAGE.jpg',
                    type: 'image/jpeg',
                    url:
                        'https://websiter.s3.amazonaws.com/5e95a4375da9c91a2716debc/ABOUT-US-_IMAGE.jpg',
                    v: 1,
                    resolution: { width: 1929, height: 1284 },
                    modifiedDate: 1590249676711,
                    createdDate: 1590249676711,
                    relUrl: '/ABOUT-US-_IMAGE.jpg',
                },
                {
                    id: 'file_3',
                    path: [],
                    size: 1895,
                    name: '120X120logo.png',
                    serverName: '5e95a4375da9c91a2716debc/120X120logo.png',
                    type: 'image/png',
                    url:
                        'https://websiter.s3.amazonaws.com/5e95a4375da9c91a2716debc/120X120logo.png',
                    v: 1,
                    resolution: { width: 120, height: 120 },
                    modifiedDate: 1588195081119,
                    createdDate: 1588195081120,
                    relUrl: '/120X120logo.png',
                },
                {
                    id: 'file_13',
                    path: [],
                    size: 10,
                    name: 'New file.css',
                    serverName: '5e95a4375da9c91a2716debc/New_file.css_1',
                    type: 'text/css',
                    url:
                        'https://websiter.s3.amazonaws.com/5e95a4375da9c91a2716debc/New_file.css_1',
                    v: 2,
                    resolution: { width: 'unknown', height: 'unknown' },
                    modifiedDate: 1588692153401,
                    createdDate: 1588692143462,
                    relUrl: '/New file.css',
                    editorMode: 'css',
                },
                {
                    id: 'file_15',
                    path: [],
                    size: 18,
                    name: 'New file.css (copy)',
                    serverName: '5e95a4375da9c91a2716debc/New_file.css__copy_',
                    type: 'text/css',
                    editorMode: 'css',
                    url:
                        'https://websiter.s3.amazonaws.com/5e95a4375da9c91a2716debc/New_file.css__copy_',
                    v: 1,
                    resolution: { width: 'unknown', height: 'unknown' },
                    modifiedDate: 1588692691939,
                    createdDate: 1588692691939,
                    relUrl: '/New file.css (copy)',
                },
                {
                    id: 'file_16',
                    path: [],
                    size: 205925,
                    name: 'download.png',
                    serverName: '5e95a4375da9c91a2716debc/download.png',
                    type: 'image/png',
                    url:
                        'https://websiter.s3.amazonaws.com/5e95a4375da9c91a2716debc/download.png',
                    v: 1,
                    resolution: { width: 300, height: 234 },
                    modifiedDate: 1589468879175,
                    createdDate: 1589468879176,
                    relUrl: '/download.png',
                },
                {
                    id: 'file_1',
                    path: [],
                    size: 6994,
                    name: '120 (5)',
                    serverName: '5e95a4375da9c91a2716debc/120__5_',
                    type: 'image/png',
                    url:
                        'https://websiter.s3.amazonaws.com/5e95a4375da9c91a2716debc/120__5_',
                    v: 1,
                    resolution: { width: 120, height: 60 },
                    modifiedDate: 1587851587909,
                    createdDate: 1587851587909,
                    relUrl: '/120 (5)',
                },
                {
                    id: 'file_5',
                    path: [],
                    size: 2152385,
                    name: 'prijava_ready.pdf',
                    serverName: '5e95a4375da9c91a2716debc/prijava_ready.pdf',
                    type: 'application/pdf',
                    url:
                        'https://websiter.s3.amazonaws.com/5e95a4375da9c91a2716debc/prijava_ready.pdf',
                    v: 1,
                    resolution: { width: 'unknown', height: 'unknown' },
                    modifiedDate: 1588196382045,
                    createdDate: 1588196382045,
                    relUrl: '/prijava_ready.pdf',
                },
                {
                    id: 'file_4',
                    path: [],
                    size: 41834,
                    name: 'a413429cd71ece7a35c6edd644f542a3.ico.zip',
                    serverName:
                        '5e95a4375da9c91a2716debc/a413429cd71ece7a35c6edd644f542a3.ico.zip',
                    type: 'application/zip',
                    url:
                        'https://websiter.s3.amazonaws.com/5e95a4375da9c91a2716debc/a413429cd71ece7a35c6edd644f542a3.ico.zip',
                    v: 1,
                    resolution: { width: 'unknown', height: 'unknown' },
                    modifiedDate: 1588195579646,
                    createdDate: 1588195579646,
                    relUrl: '/a413429cd71ece7a35c6edd644f542a3.ico.zip',
                },
                {
                    id: 'file_20',
                    path: [],
                    size: 2326629,
                    name: 'service__--_image.png',
                    serverName:
                        '5e95a4375da9c91a2716debc/service__--_image.png',
                    type: 'image/png',
                    url:
                        'https://websiter.s3.amazonaws.com/5e95a4375da9c91a2716debc/service__--_image.png',
                    v: 1,
                    resolution: { width: 1929, height: 1284 },
                    modifiedDate: 1590485956190,
                    createdDate: 1590485956190,
                    relUrl: '/service__--_image.png',
                },
            ],
            pagesStructure: [
                {
                    id: '5e95a4375da9c91a2716debd',
                    name: 'Global website settings',
                    url: '__general__settings__',
                    hidden: true,
                    path: [],
                    published: true,
                    generalSettings: true,
                    template: 'Global website settings',
                    relUrl: '/__general__settings__',
                    homepage: false,
                    isHomePage: true,
                    expanded: true,
                },
                {
                    id: '5e95a4485da9c91a2716debf',
                    path: [],
                    name: 'New page',
                    url: 'new-page',
                    hidden: false,
                    published: false,
                    homepage: false,
                    relUrl: '/new-page',
                    template: 'New template 2',
                    expanded: true,
                },
                {
                    id: '5eab82022548796bd4100df9',
                    path: [],
                    name: 'New page 10',
                    url: 'new-page-10',
                    hidden: false,
                    published: true,
                    homepage: false,
                    relUrl: '/new-page-10',
                    expanded: true,
                },
                {
                    id: '5eb18f508304356a8988ea62',
                    path: ['5eab82022548796bd4100df9'],
                    name: 'New page 11',
                    url: '12123__',
                    hidden: false,
                    published: true,
                    homepage: false,
                    relUrl: '/new-page-10/12123__',
                    expanded: true,
                },
                {
                    id: '5eab82012548796bd4100df7',
                    path: [
                        '5eab82022548796bd4100df9',
                        '5eb18f508304356a8988ea62',
                    ],
                    name: 'New page 7',
                    url: 'new-page-7',
                    hidden: false,
                    published: true,
                    homepage: false,
                    relUrl: '/new-page-10/12123__/new-page-7',
                    expanded: true,
                },
                {
                    id: '5eab82012548796bd4100df6',
                    path: [
                        '5eab82022548796bd4100df9',
                        '5eb18f508304356a8988ea62',
                    ],
                    name: 'New page 6',
                    url: 'new-page-6',
                    hidden: false,
                    published: true,
                    homepage: false,
                    relUrl: '/new-page-10/12123__/new-page-6',
                    expanded: true,
                    template: 'New template 1',
                },
                {
                    id: '5eabe2872548796bd4100dfa',
                    path: [],
                    name: 'New page 6 1',
                    url: 'new-page-6-1',
                    template: 'New template 1 1',
                    hidden: false,
                    published: false,
                    homepage: false,
                    relUrl: '/new-page-6-1',
                    expanded: true,
                },
                {
                    id: '5eab82002548796bd4100df5',
                    path: ['5eabe2872548796bd4100dfa'],
                    name: 'New page 5',
                    url: 'new-page-5',
                    hidden: false,
                    published: true,
                    homepage: false,
                    relUrl: '/new-page-6-1/new-page-5',
                    expanded: true,
                },
                {
                    id: '5eab82002548796bd4100df4',
                    path: [],
                    name: 'New page 4',
                    url: 'new-page-4',
                    hidden: true,
                    published: true,
                    homepage: false,
                    relUrl: '/new-page-4',
                    expanded: true,
                },
                {
                    id: '5eab82002548796bd4100df3',
                    path: [],
                    name: 'New page 3',
                    url: 'new-page-3',
                    hidden: true,
                    published: true,
                    homepage: false,
                    relUrl: '/new-page-3',
                    expanded: true,
                },
                {
                    id: '5ea3620132240062a50b052c',
                    path: [],
                    name:
                        'Guide for admins and xczxcxzc sdfds sdfds fdsf sdfzxczxwebsite owners',
                    url: 'new-page-1',
                    hidden: false,
                    published: true,
                    homepage: false,
                    relUrl: '/new-page-1',
                    template: 'New template 1',
                    connectedResources: null,
                    folderPage: true,
                },
                {
                    id: '5eab81ff2548796bd4100df2',
                    path: [],
                    name: 'New page 2',
                    url: 'new-page-2',
                    hidden: true,
                    published: true,
                    homepage: false,
                    relUrl: '/new-page-2',
                    expanded: true,
                },
                {
                    id: '5eab7d3c2548796bd4100df0',
                    path: [],
                    name: 'New page 8',
                    url: 'new-page-8',
                    hidden: false,
                    published: true,
                    homepage: false,
                    relUrl: '/new-page-8',
                    folderPage: true,
                    template: 'New template 2',
                    connectedResources: null,
                },
            ],
            pluginsStructure: [
                {
                    id: '5ea44c0432240062a50b052d',
                    path: [],
                    name: 'GG',
                    published: false,
                    hidden: false,
                    connectedResources: [],
                    propagating: true,
                },
                {
                    id: '5eb198888304356a8988ea63',
                    path: [],
                    name: 'FF',
                    published: true,
                },
                {
                    id: '5eb1990f8304356a8988ea64',
                    path: [],
                    name: 'Plu',
                    published: true,
                    propagating: true,
                },
            ],
            templatesStructure: [
                {
                    id: '5e95a4375da9c91a2716debe',
                    name: 'Global website settings',
                    url: '__general__settings__',
                    hidden: true,
                    path: [],
                    published: true,
                    generalSettings: true,
                },
                {
                    id: '5e95a4545da9c91a2716dec0',
                    path: [],
                    name: 'New template',
                    published: false,
                    connectedResources: [],
                    hidden: false,
                },
                {
                    id: '5e95c91b5da9c91a2716dec1',
                    path: [],
                    name: 'New template 1',
                    published: false,
                    hidden: false,
                    connectedResources: [
                        { name: 'New CMS variable', type: 'plugin' },
                        { name: 'GG', type: 'plugin' },
                    ],
                },
                {
                    id: '5eabe44e2548796bd4100dfb',
                    path: [],
                    name: 'New template 1 1',
                    published: true,
                    connectedResources: [
                        { name: 'New CMS variable', type: 'plugin' },
                        { name: 'One', type: 'plugin' },
                        { name: 'OOOO', type: 'plugin' },
                        { name: 'Two', type: 'plugin' },
                        { name: 'TTTT', type: 'plugin' },
                        { name: 'VVVVVVV', type: 'plugin' },
                        { name: 'SSSSSSSSS', type: 'plugin' },
                        { name: 'GG', type: 'plugin' },
                    ],
                },
                {
                    id: '5ea5a4a3a49095490f9d88b9',
                    path: [],
                    name: 'New template 2',
                    published: false,
                    connectedResources: [
                        { name: 'New CMS variable', type: 'plugin' },
                    ],
                },
            ],
            _id: '5e95a4375da9c91a2716debc',
            name: 'New website',
            domain: 'new-website-12',
            user: '5e95a4375da9c91a2716debb',
            storage: 0,
            __v: 302,
            __patch__: {
                sharing: {
                    '0': [
                        {
                            userId: '5e95a4375da9c91a2716debb',
                            rights: ['owner', 'admin', 'content', 'developer'],
                            accountInfo: {
                                displayName: null,
                                photos: [
                                    {
                                        value:
                                            'https://avatars0.githubusercontent.com/u/7085000?v=4',
                                    },
                                ],
                            },
                        },
                    ],
                    _t: 'a',
                    _0: [
                        {
                            userId: '5e95a4375da9c91a2716debb',
                            rights: ['owner', 'admin', 'content', 'developer'],
                            accountInfo: {
                                displayName: null,
                                photos: [
                                    {
                                        value:
                                            'https://avatars0.githubusercontent.com/u/7085000?v=4',
                                    },
                                ],
                            },
                        },
                        0,
                        0,
                    ],
                },
                templatesStructure: {
                    '2': {
                        connectedResources: {
                            '0': [{ name: 'New CMS variable', type: 'plugin' }],
                            '1': [{ name: 'GG', type: 'plugin' }],
                            _t: 'a',
                            _0: [
                                { name: 'New CMS variable', type: 'plugin' },
                                0,
                                0,
                            ],
                            _1: [{ name: 'GG', type: 'plugin' }, 0, 0],
                        },
                    },
                    '3': {
                        connectedResources: {
                            '0': [{ name: 'New CMS variable', type: 'plugin' }],
                            '1': [{ name: 'One', type: 'plugin' }],
                            '2': [{ name: 'OOOO', type: 'plugin' }],
                            '3': [{ name: 'Two', type: 'plugin' }],
                            '4': [{ name: 'TTTT', type: 'plugin' }],
                            '5': [{ name: 'VVVVVVV', type: 'plugin' }],
                            '6': [{ name: 'SSSSSSSSS', type: 'plugin' }],
                            '7': [{ name: 'GG', type: 'plugin' }],
                            _t: 'a',
                            _0: [
                                { name: 'New CMS variable', type: 'plugin' },
                                0,
                                0,
                            ],
                            _1: [{ name: 'One', type: 'plugin' }, 0, 0],
                            _2: [{ name: 'OOOO', type: 'plugin' }, 0, 0],
                            _3: [{ name: 'Two', type: 'plugin' }, 0, 0],
                            _4: [{ name: 'TTTT', type: 'plugin' }, 0, 0],
                            _5: [{ name: 'VVVVVVV', type: 'plugin' }, 0, 0],
                            _6: [{ name: 'SSSSSSSSS', type: 'plugin' }, 0, 0],
                            _7: [{ name: 'GG', type: 'plugin' }, 0, 0],
                        },
                    },
                    '4': {
                        connectedResources: {
                            '0': [{ name: 'New CMS variable', type: 'plugin' }],
                            _t: 'a',
                            _0: [
                                { name: 'New CMS variable', type: 'plugin' },
                                0,
                                0,
                            ],
                        },
                    },
                    _t: 'a',
                },
            },
            nextFileId: 21,
            domainHidden: false,
        },
        '5ece8684273f8145e5f04439': {
            sharing: [
                {
                    userId: '5e95a4375da9c91a2716debb',
                    rights: ['owner', 'admin', 'developer', 'content'],
                    accountInfo: {
                        displayName: null,
                        photos: [
                            {
                                value:
                                    'https://avatars0.githubusercontent.com/u/7085000?v=4',
                            },
                        ],
                    },
                },
            ],
            filesStructure: [],
            pagesStructure: [
                {
                    id: '5ece8684273f8145e5f0443a',
                    name: 'Global website settings',
                    url: '__general__settings__',
                    hidden: true,
                    path: [],
                    published: true,
                    generalSettings: true,
                    template: 'Global website settings',
                    relUrl: '/__general__settings__',
                    homepage: false,
                    isHomePage: true,
                },
            ],
            pluginsStructure: [
                {
                    id: '5ed4dd3058cd1e16badab1de',
                    path: [],
                    name: 'Lola',
                    published: true,
                },
            ],
            templatesStructure: [
                {
                    id: '5ece8684273f8145e5f0443b',
                    name: 'Global website settings',
                    url: '__general__settings__',
                    hidden: true,
                    path: [],
                    published: true,
                    generalSettings: true,
                },
                {
                    id: '5ed4dde158cd1e16badab1e0',
                    path: [],
                    name: 'New template',
                    published: false,
                },
            ],
            _id: '5ece8684273f8145e5f04439',
            name: 'New website',
            domain: 'new-website-13',
            user: '5e95a4375da9c91a2716debb',
            storage: 0,
            __v: 36,
            __patch__: {
                sharing: {
                    '0': [
                        {
                            userId: '5e95a4375da9c91a2716debb',
                            rights: ['owner', 'admin', 'developer', 'content'],
                            accountInfo: {
                                displayName: null,
                                photos: [
                                    {
                                        value:
                                            'https://avatars0.githubusercontent.com/u/7085000?v=4',
                                    },
                                ],
                            },
                        },
                    ],
                    _t: 'a',
                    _0: [
                        {
                            userId: '5e95a4375da9c91a2716debb',
                            rights: ['owner', 'admin', 'developer', 'content'],
                            accountInfo: {
                                displayName: null,
                                photos: [
                                    {
                                        value:
                                            'https://avatars0.githubusercontent.com/u/7085000?v=4',
                                    },
                                ],
                            },
                        },
                        0,
                        0,
                    ],
                },
                pluginsStructure: {
                    _t: 'a',
                    _1: [
                        {
                            id: '5ed4f59e35b6740e8fd6b30d',
                            path: [],
                            name: 'New plugin',
                            published: true,
                        },
                        0,
                        0,
                    ],
                },
            },
        },
        '5ece8684273f8145e5f0443a': {
            draft: { structure: [], values: {}, connectedResources: [] },
            present: {},
            future: [],
            past: [],
            __v: 0,
            _id: '5ece8684273f8145e5f0443a',
        },
        '5ed4dd3058cd1e16badab1de': {
            draft: {
                currentId: 1,
                structure: [{ id: 'element_0', path: [], tag: 'Main element' }],
                values: { element_0: { properties: {} } },
                connectedResources: [],
            },
            present: {
                currentId: 2,
                structure: [
                    {
                        id: 'element_0',
                        tag: 'Main element',
                        itemPath: [],
                        expanded: true,
                        path: [],
                    },
                    {
                        id: 'element_1',
                        tag: 'TestChild',
                        isPropagatingItem: false,
                        textMode: 'text',
                        text: false,
                        isChildren: true,
                        isCMSVariable: false,
                        isElementFromCMSVariable: false,
                        itemPath: ['element_0'],
                        path: ['element_0'],
                    },
                ],
                values: {
                    element_0: { properties: {} },
                    element_1: {
                        textContent: '',
                        properties: {},
                        propertiesString: '',
                        CMSVariableType: 'text',
                        CMSVariableSystemName: 'newCmsVariable',
                        CMSVariableDescription: 'New CMS variable description',
                        CMSVariableDefaultValue:
                            'New CMS variable default value',
                    },
                },
                connectedResources: [],
                currentBox: 'element_1',
            },
            future: [],
            past: [],
            __v: 0,
            _id: '5ed4dd3058cd1e16badab1de',
        },
        '5ece8684273f8145e5f0443b': {
            draft: {
                currentId: 3,
                structure: [
                    { id: 'element_02', path: [], tag: 'CMS variables' },
                ],
                values: { element_02: { properties: {}, style: '' } },
                connectedResources: [],
            },
            present: {},
            future: [],
            past: [],
            __v: 0,
            _id: '5ece8684273f8145e5f0443b',
        },
        '5ed4dde158cd1e16badab1e0': {
            draft: {
                currentId: 3,
                structure: [
                    {
                        id: 'element_02',
                        path: [],
                        tag: 'CMS variables',
                        itemPath: [],
                    },
                    {
                        id: 'element_01',
                        path: [],
                        tag: 'html',
                        itemPath: [],
                        expanded: true,
                    },
                    {
                        id: 'element_0',
                        path: ['element_01'],
                        tag: 'head',
                        itemPath: ['element_01'],
                    },
                    {
                        id: 'element_1',
                        path: ['element_01'],
                        tag: 'body',
                        itemPath: ['element_01'],
                        expanded: true,
                    },
                    {
                        id: 'element_2',
                        path: ['element_01', 'element_1'],
                        tag: 'Lola',
                        itemPath: ['element_01', 'element_1'],
                        expanded: true,
                    },
                    {
                        id:
                            'element_2_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_1',
                        childrenTo: 'element_1',
                        forPlugin: '5ed4dd3058cd1e16badab1de',
                        sourcePlugin: '',
                        text: false,
                        isChildren: false,
                        forChildren: true,
                        tag: 'Children for TestChild',
                        itemPath: ['element_01', 'element_1', 'element_2'],
                        path: ['element_01', 'element_1', 'element_2'],
                    },
                ],
                values: {
                    element_02: { properties: {}, style: '' },
                    element_01: { properties: {}, style: '' },
                    element_0: { properties: {}, style: '' },
                    element_1: { properties: {}, style: '' },
                    element_2: {
                        properties: {},
                        style:
                            'height: 100px;width: 100px;left: 200px;top: 100px;z-index: 0;background: rgba(100, 0, 80);',
                    },
                },
                connectedResources: [{ name: 'Lola', type: 'plugin' }],
                currentBox: 'element_2',
            },
            present: {
                currentId: 3,
                structure: [
                    {
                        id: 'element_02',
                        tag: 'CMS variables',
                        itemPath: [],
                        path: [],
                    },
                    {
                        id: 'element_01',
                        tag: 'html',
                        itemPath: [],
                        expanded: true,
                        path: [],
                    },
                    {
                        id: 'element_0',
                        tag: 'head',
                        itemPath: ['element_01'],
                        path: ['element_01'],
                    },
                    {
                        id: 'element_1',
                        tag: 'body',
                        itemPath: ['element_01'],
                        expanded: true,
                        path: ['element_01'],
                    },
                    {
                        id: 'element_2',
                        tag: 'Lola',
                        itemPath: ['element_01', 'element_1'],
                        expanded: true,
                        path: ['element_01', 'element_1'],
                    },
                    {
                        id:
                            'element_2_forPlugin_5ed4dd3058cd1e16badab1de_childrenTo_element_1',
                        childrenTo: 'element_1',
                        forPlugin: '5ed4dd3058cd1e16badab1de',
                        sourcePlugin: '',
                        path: ['element_01', 'element_1', 'element_2'],
                        text: false,
                        isChildren: false,
                        forChildren: true,
                        tag: 'Children for New children',
                    },
                ],
                values: {
                    element_02: { properties: {}, style: '' },
                    element_01: { properties: {}, style: '' },
                    element_0: { properties: {}, style: '' },
                    element_1: { properties: {}, style: '' },
                    element_2: {
                        properties: {},
                        style:
                            'height: 100px;width: 100px;left: 200px;top: 100px;z-index: 0;background: rgba(100, 0, 80);',
                    },
                },
                connectedResources: [{ name: 'Lola', type: 'plugin' }],
                currentBox: 'element_2',
            },
            future: [],
            past: [],
            __v: 1,
            _id: '5ed4dde158cd1e16badab1e0',
        },
    },
    userId: '5e95a4375da9c91a2716debb',
    nextFileId: 0,
    prod: false,
}
