export default [
    'page',
    {
        currentId: 2,
        structure: [
            {
                CMSVariableType: 'array',
                expanded: true,
                id: 'element_3',
                isCMSVariable: false,
                isChildren: false,
                isElementFromCMSVariable: false,
                isPropagatingItem: false,
                path: [],
                tag: 'New CMS variable',
                text: false,
                textMode: 'text',
            },
            {
                id: 'elementCMS_0',
                isCMSVariable: false,
                isChildren: false,
                isElementFromCMSVariable: false,
                isPropagatingItem: true,
                path: ['element_3'],
                tag: 'Item',
                text: false,
                textMode: 'text',
            },
            {
                CMSVariableType: 'propagating_5eced39bc0059c520d6c18be',
                expanded: undefined,
                forPropagatingPlugin: {
                    pluginId: '5ece8696273f8145e5f0443c',
                    variable: 'element_4',
                },
                id: 'elementCMS_1',
                isCMSVariable: false,
                isChildren: false,
                isElementFromCMSVariable: false,
                isPropagatingItem: false,
                path: ['element_3', 'elementCMS_0'],
                tag: 'New CMS variable',
                text: false,
                textMode: 'text',
            },
        ],
        values: {
            elementCMS_0: {
                CMSVariableDefaultValue: 'New CMS variable default value',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableType: 'text',
                properties: {},
                propertiesString: '',
                textContent: '',
            },
            elementCMS_1: {
                CMSVariableDefaultValue: 'New CMS variable default value',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableType: 'propagating_5eced39bc0059c520d6c18be',
                currentMenuId: 0,
                currentMenuItem: '',
                menuItems: [],
                properties: {},
                propertiesString: '',
                textContent: '',
                value: '',
            },
            element_3: {
                CMSVariableDefaultValue: 'New CMS variable default value',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableType: 'array',
                currentMenuId: 0,
                currentMenuItem: '',
                menuItems: [],
                properties: {},
                propertiesString: '',
                textContent: '',
                value: '',
            },
        },
    },
    false,
]
