export default [
    'page',
    {
        currentId: 24,
        structure: [
            {
                id: 'element_3',
                tag: 'Array ',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                expanded: true,
                path: [],
                CMSVariableType: 'array',
            },
            {
                id: 'elementCMS_0',
                tag: 'Item',
                isPropagatingItem: true,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                expanded: true,
                path: ['element_3'],
            },
            {
                id: 'elementCMS_1',
                tag: 'Plugin',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                expanded: true,
                path: ['element_3', 'elementCMS_0'],
                forPropagatingPlugin: {
                    pluginId: '5ece8696273f8145e5f0443c',
                    variable: 'element_4',
                },
                CMSVariableType: 'propagating_5eced39bc0059c520d6c18be',
            },
            {
                id: 'elementCMS_4',
                tag: 'Item',
                isPropagatingItem: true,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                expanded: true,
                path: ['element_3', 'elementCMS_0', 'elementCMS_1'],
            },
            {
                id: 'elementCMS_20',
                tag: 'I am in Plugin',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                path: [
                    'element_3',
                    'elementCMS_0',
                    'elementCMS_1',
                    'elementCMS_4',
                ],
                forPropagatingPlugin: {
                    pluginId: '5eced39bc0059c520d6c18be',
                    variable: 'element_1',
                },
                CMSVariableType: 'number',
            },
            {
                id: 'elementCMS_5',
                tag: 'Item',
                isPropagatingItem: true,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                expanded: true,
                path: ['element_3', 'elementCMS_0', 'elementCMS_1'],
            },
            {
                id: 'elementCMS_21',
                tag: 'I am in Plugin',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                path: [
                    'element_3',
                    'elementCMS_0',
                    'elementCMS_1',
                    'elementCMS_5',
                ],
                forPropagatingPlugin: {
                    pluginId: '5eced39bc0059c520d6c18be',
                    variable: 'element_1',
                },
                CMSVariableType: 'number',
            },
            {
                id: 'elementCMS_8',
                tag: 'Array 2',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                expanded: true,
                path: ['element_3', 'elementCMS_0'],
                forPropagatingPlugin: {
                    pluginId: '5ece8696273f8145e5f0443c',
                    variable: 'element_5',
                },
                CMSVariableType: 'array',
            },
            {
                id: 'elementCMS_16',
                tag: 'Item',
                isPropagatingItem: true,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                expanded: true,
                path: ['element_3', 'elementCMS_0', 'elementCMS_8'],
            },
            {
                id: 'elementCMS_17',
                tag: 'I am in array 2',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                path: [
                    'element_3',
                    'elementCMS_0',
                    'elementCMS_8',
                    'elementCMS_16',
                ],
                forPropagatingPlugin: {
                    pluginId: '5ece8696273f8145e5f0443c',
                    variable: 'element_6',
                },
                CMSVariableType: 'propagating_5eced39bc0059c520d6c18be',
                expanded: true,
            },
            {
                id: 'elementCMS_18',
                tag: 'Item',
                isPropagatingItem: true,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                expanded: true,
                path: [
                    'element_3',
                    'elementCMS_0',
                    'elementCMS_8',
                    'elementCMS_16',
                    'elementCMS_17',
                ],
            },
            {
                id: 'elementCMS_22',
                tag: 'I am in Plugin',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                path: [
                    'element_3',
                    'elementCMS_0',
                    'elementCMS_8',
                    'elementCMS_16',
                    'elementCMS_17',
                    'elementCMS_18',
                ],
                forPropagatingPlugin: {
                    pluginId: '5eced39bc0059c520d6c18be',
                    variable: 'element_1',
                },
                CMSVariableType: 'number',
            },
            {
                id: 'elementCMS_9',
                tag: 'Item',
                isPropagatingItem: true,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                expanded: true,
                path: ['element_3'],
            },
            {
                id: 'elementCMS_10',
                tag: 'Plugin',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                expanded: true,
                path: ['element_3', 'elementCMS_9'],
                forPropagatingPlugin: {
                    pluginId: '5ece8696273f8145e5f0443c',
                    variable: 'element_4',
                },
                CMSVariableType: 'propagating_5eced39bc0059c520d6c18be',
            },
            {
                id: 'elementCMS_12',
                tag: 'Item',
                isPropagatingItem: true,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                expanded: true,
                path: ['element_3', 'elementCMS_9', 'elementCMS_10'],
            },
            {
                id: 'elementCMS_23',
                tag: 'I am in Plugin',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                path: [
                    'element_3',
                    'elementCMS_9',
                    'elementCMS_10',
                    'elementCMS_12',
                ],
                forPropagatingPlugin: {
                    pluginId: '5eced39bc0059c520d6c18be',
                    variable: 'element_1',
                },
                CMSVariableType: 'number',
            },
            {
                id: 'elementCMS_11',
                tag: 'Array 2',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                path: ['element_3', 'elementCMS_9'],
                forPropagatingPlugin: {
                    pluginId: '5ece8696273f8145e5f0443c',
                    variable: 'element_5',
                },
                CMSVariableType: 'array',
            },
            { id: 'trash', tag: 'Trash', path: [] },
            {
                id: 'elementCMS_2',
                tag: 'Item',
                isPropagatingItem: true,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                expanded: true,
                path: ['trash'],
            },
            {
                id: 'elementCMS_3',
                tag: 'New CMS variable',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                forPropagatingPlugin: {
                    pluginId: '5ece8696273f8145e5f0443c',
                    variable: 'element_4',
                },
                CMSVariableType: 'propagating_5eced39bc0059c520d6c18be',
                path: ['trash', 'elementCMS_2'],
            },
        ],
        values: {
            element_3: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'array',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                value: '',
                menuItems: [],
                currentMenuItem: '',
                currentMenuId: 0,
            },
            elementCMS_1: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'propagating_5eced39bc0059c520d6c18be',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                value: '',
                menuItems: [],
                currentMenuItem: '',
                currentMenuId: 0,
            },
            elementCMS_20: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'number',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                value: '',
                menuItems: [],
                currentMenuItem: '',
                currentMenuId: 0,
            },
            elementCMS_4: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'text',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
            },
            elementCMS_21: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'number',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                value: '',
                menuItems: [],
                currentMenuItem: '',
                currentMenuId: 0,
            },
            elementCMS_5: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'text',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
            },
            elementCMS_8: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'array',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                value: '',
                menuItems: [],
                currentMenuItem: '',
                currentMenuId: 0,
            },
            elementCMS_17: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'propagating_5eced39bc0059c520d6c18be',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                value: '',
                menuItems: [],
                currentMenuItem: '',
                currentMenuId: 0,
            },
            elementCMS_22: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'number',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                value: '',
                menuItems: [],
                currentMenuItem: '',
                currentMenuId: 0,
            },
            elementCMS_18: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'text',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
            },
            elementCMS_16: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'text',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
            },
            elementCMS_0: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'text',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
            },
            elementCMS_10: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'propagating_5eced39bc0059c520d6c18be',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                value: '',
                menuItems: [],
                currentMenuItem: '',
                currentMenuId: 0,
            },
            elementCMS_23: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'number',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                value: '',
                menuItems: [],
                currentMenuItem: '',
                currentMenuId: 0,
            },
            elementCMS_12: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'text',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
            },
            elementCMS_11: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'array',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                value: '',
                menuItems: [],
                currentMenuItem: '',
                currentMenuId: 0,
            },
            elementCMS_9: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'text',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
            },
            trash: { properties: {}, style: '' },
            elementCMS_2: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'text',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
            },
            elementCMS_3: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'propagating_5eced39bc0059c520d6c18be',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                value: '',
                menuItems: [],
                currentMenuItem: '',
                currentMenuId: 0,
            },
        },
    },
    false,
]
