export default {
    userObject: {
        websites: [{ id: '5ed6478aec5aa62ae89844a0' }],
        settings: {
            websites: {
                '5ed6478aec5aa62ae89844a0': {
                    currentPageFSBId: '5ed6af842c0e9615bc6e15ae',
                    currentPageId: '5ed6af842c0e9615bc6e15ae',
                },
            },
            currentWebsite: '5ed6478aec5aa62ae89844a0',
        },
        logoutAllDate: 1591100722138,
        _id: '5ed6478aec5aa62ae898449f',
        userid: '7085000',
        platformId: 'github',
        accountInfo: {
            displayName: null,
            photos: [
                {
                    value:
                        'https://avatars0.githubusercontent.com/u/7085000?v=4',
                },
            ],
        },
        __v: 0,
    },
    websites: [{ id: '5ed6478aec5aa62ae89844a0' }],
    currentWebsiteItem: { id: '5ed6478aec5aa62ae89844a0' },
    currentWebsiteId: '5ed6478aec5aa62ae89844a0',
    currentWebsiteObject: {
        sharing: [
            {
                userId: '5ed6478aec5aa62ae898449f',
                rights: ['owner', 'admin', 'developer', 'content'],
                accountInfo: {
                    displayName: null,
                    photos: [
                        {
                            value:
                                'https://avatars0.githubusercontent.com/u/7085000?v=4',
                        },
                    ],
                },
            },
        ],
        filesStructure: [],
        pagesStructure: [
            {
                id: '5ed6478aec5aa62ae89844a1',
                name: 'Global website settings',
                url: '__general__settings__',
                hidden: true,
                path: [],
                published: true,
                generalSettings: true,
                template: 'Global website settings',
                relUrl: '/__general__settings__',
            },
            {
                id: '5ed6af842c0e9615bc6e15ae',
                path: [],
                name: 'New page',
                url: 'new-page',
                hidden: true,
                published: true,
                homepage: false,
                relUrl: '/new-page',
                template: 'TestTemp',
                connectedResources: null,
            },
        ],
        pluginsStructure: [
            {
                id: '5ed6aebb2c0e9615bc6e15ac',
                path: [],
                name: 'TestPlug',
                published: true,
                propagating: true,
                connectedResources: [
                    { name: 'TestVar1', type: 'plugin' },
                    { name: 'TestVar2', type: 'plugin' },
                    { name: 'TestVar3', type: 'plugin' },
                ],
            },
        ],
        templatesStructure: [
            {
                id: '5ed6478aec5aa62ae89844a2',
                name: 'Global website settings',
                url: '__general__settings__',
                hidden: true,
                path: [],
                published: true,
                generalSettings: true,
            },
            {
                id: '5ed6af242c0e9615bc6e15ad',
                path: [],
                name: 'TestTemp',
                published: true,
                connectedResources: [
                    { name: 'TestPlugVar', type: 'plugin' },
                    { name: 'TestPlug', type: 'plugin' },
                ],
            },
        ],
        _id: '5ed6478aec5aa62ae89844a0',
        name: 'New website',
        domain: 'new-website-3',
        user: '5ed6478aec5aa62ae898449f',
        storage: 0,
        __v: 13,
        __patch__: {
            sharing: {
                '0': [
                    {
                        userId: '5ed6478aec5aa62ae898449f',
                        rights: ['owner', 'admin', 'developer', 'content'],
                        accountInfo: {
                            displayName: null,
                            photos: [
                                {
                                    value:
                                        'https://avatars0.githubusercontent.com/u/7085000?v=4',
                                },
                            ],
                        },
                    },
                ],
                _t: 'a',
                _0: [
                    {
                        userId: '5ed6478aec5aa62ae898449f',
                        rights: ['owner', 'admin', 'developer', 'content'],
                        accountInfo: {
                            displayName: null,
                            photos: [
                                {
                                    value:
                                        'https://avatars0.githubusercontent.com/u/7085000?v=4',
                                },
                            ],
                        },
                    },
                    0,
                    0,
                ],
            },
            pagesStructure: { '1': { published: [false, true] }, _t: 'a' },
            pluginsStructure: {
                '0': {
                    connectedResources: {
                        '0': [{ name: 'TestVar1', type: 'plugin' }],
                        '1': [{ name: 'TestVar2', type: 'plugin' }],
                        '2': [{ name: 'TestVar3', type: 'plugin' }],
                        _t: 'a',
                        _0: [{ name: 'TestVar1', type: 'plugin' }, 0, 0],
                        _1: [{ name: 'TestVar2', type: 'plugin' }, 0, 0],
                        _2: [{ name: 'TestVar3', type: 'plugin' }, 0, 0],
                    },
                },
                _t: 'a',
            },
            templatesStructure: {
                '1': {
                    connectedResources: {
                        '0': [{ name: 'TestPlugVar', type: 'plugin' }],
                        '1': [{ name: 'TestPlug', type: 'plugin' }],
                        _t: 'a',
                        _0: [{ name: 'TestPlugVar', type: 'plugin' }, 0, 0],
                        _1: [{ name: 'TestPlug', type: 'plugin' }, 0, 0],
                    },
                },
                _t: 'a',
            },
        },
    },
    pagesStructure: [
        {
            id: '5ed6478aec5aa62ae89844a1',
            name: 'Global website settings',
            url: '__general__settings__',
            hidden: true,
            path: [],
            published: true,
            generalSettings: true,
            template: 'Global website settings',
            relUrl: '/__general__settings__',
        },
        {
            id: '5ed6af842c0e9615bc6e15ae',
            path: [],
            name: 'New page',
            url: 'new-page',
            hidden: true,
            published: true,
            homepage: false,
            relUrl: '/new-page',
            template: 'TestTemp',
            connectedResources: null,
        },
    ],
    templatesStructure: [
        {
            id: '5ed6478aec5aa62ae89844a2',
            name: 'Global website settings',
            url: '__general__settings__',
            hidden: true,
            path: [],
            published: true,
            generalSettings: true,
        },
        {
            id: '5ed6af242c0e9615bc6e15ad',
            path: [],
            name: 'TestTemp',
            published: true,
            connectedResources: [
                { name: 'TestPlugVar', type: 'plugin' },
                { name: 'TestPlug', type: 'plugin' },
            ],
        },
    ],
    pluginsStructure: [
        {
            id: '5ed6aebb2c0e9615bc6e15ac',
            path: [],
            name: 'TestPlug',
            published: true,
            propagating: true,
            connectedResources: [
                { name: 'TestVar1', type: 'plugin' },
                { name: 'TestVar2', type: 'plugin' },
                { name: 'TestVar3', type: 'plugin' },
            ],
        },
    ],
    filesStructure: [],
    currentPageId: '5ed6af842c0e9615bc6e15ae',
    currentPageFSBId: '5ed6af842c0e9615bc6e15ae',
    currentPageItem: {
        id: '5ed6af842c0e9615bc6e15ae',
        path: [],
        name: 'New page',
        url: 'new-page',
        hidden: true,
        published: true,
        homepage: false,
        relUrl: '/new-page',
        template: 'TestTemp',
        connectedResources: null,
    },
    currentPageFSBItem: {
        id: '5ed6af842c0e9615bc6e15ae',
        path: [],
        name: 'New page',
        url: 'new-page',
        hidden: true,
        published: true,
        homepage: false,
        relUrl: '/new-page',
        template: 'TestTemp',
        connectedResources: null,
    },
    currentPageObject: {
        draft: {
            structure: [
                {
                    id: 'element_4',
                    tag: 'TestPlugVar',
                    isPropagatingItem: false,
                    textMode: 'text',
                    text: false,
                    isChildren: false,
                    isCMSVariable: false,
                    isElementFromCMSVariable: false,
                    path: [],
                    CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                },
            ],
            values: {
                element_4: {
                    textContent: '',
                    properties: {},
                    propertiesString: '',
                    CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                    CMSVariableSystemName: 'testPlugVar',
                    CMSVariableDescription: 'New CMS variable description',
                    CMSVariableDefaultValue: 'New CMS variable default value',
                    value: '',
                    menuItems: [],
                    currentMenuItem: '',
                    currentMenuId: 0,
                },
            },
            currentId: 0,
        },
        present: {
            structure: [
                {
                    id: 'element_4',
                    tag: 'TestPlugVar',
                    isPropagatingItem: false,
                    textMode: 'text',
                    text: false,
                    isChildren: false,
                    isCMSVariable: false,
                    isElementFromCMSVariable: false,
                    CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                    itemPath: [],
                    path: [],
                },
            ],
            values: {
                element_4: {
                    textContent: '',
                    properties: {},
                    propertiesString: '',
                    CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                    CMSVariableSystemName: 'testPlugVar',
                    CMSVariableDescription: 'New CMS variable description',
                    CMSVariableDefaultValue: 'New CMS variable default value',
                    value: '',
                    menuItems: [],
                    currentMenuItem: '',
                    currentMenuId: 0,
                },
            },
            currentId: 0,
            currentBox: 'element_4',
        },
        future: [],
        past: [],
        __v: 2,
        _id: '5ed6af842c0e9615bc6e15ae',
    },
    currentPageFSBObject: {
        draft: {
            structure: [
                {
                    id: 'element_4',
                    tag: 'TestPlugVar',
                    isPropagatingItem: false,
                    textMode: 'text',
                    text: false,
                    isChildren: false,
                    isCMSVariable: false,
                    isElementFromCMSVariable: false,
                    path: [],
                    CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                },
            ],
            values: {
                element_4: {
                    textContent: '',
                    properties: {},
                    propertiesString: '',
                    CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                    CMSVariableSystemName: 'testPlugVar',
                    CMSVariableDescription: 'New CMS variable description',
                    CMSVariableDefaultValue: 'New CMS variable default value',
                    value: '',
                    menuItems: [],
                    currentMenuItem: '',
                    currentMenuId: 0,
                },
            },
            currentId: 0,
        },
        present: {
            structure: [
                {
                    id: 'element_4',
                    tag: 'TestPlugVar',
                    isPropagatingItem: false,
                    textMode: 'text',
                    text: false,
                    isChildren: false,
                    isCMSVariable: false,
                    isElementFromCMSVariable: false,
                    CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                    itemPath: [],
                    path: [],
                },
            ],
            values: {
                element_4: {
                    textContent: '',
                    properties: {},
                    propertiesString: '',
                    CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                    CMSVariableSystemName: 'testPlugVar',
                    CMSVariableDescription: 'New CMS variable description',
                    CMSVariableDefaultValue: 'New CMS variable default value',
                    value: '',
                    menuItems: [],
                    currentMenuItem: '',
                    currentMenuId: 0,
                },
            },
            currentId: 0,
            currentBox: 'element_4',
        },
        future: [],
        past: [],
        __v: 2,
        _id: '5ed6af842c0e9615bc6e15ae',
    },
    currentPageDraft: {
        structure: [
            {
                id: 'element_4',
                tag: 'TestPlugVar',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                itemPath: [],
                path: [],
            },
        ],
        values: {
            element_4: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                CMSVariableSystemName: 'testPlugVar',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                value: '',
                menuItems: [],
                currentMenuItem: '',
                currentMenuId: 0,
            },
        },
        currentId: 0,
        currentBox: 'element_4',
    },
    currentPageFSBDraft: {
        structure: [
            {
                id: 'element_4',
                tag: 'TestPlugVar',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                itemPath: [],
                path: [],
            },
        ],
        values: {
            element_4: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                CMSVariableSystemName: 'testPlugVar',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                value: '',
                menuItems: [],
                currentMenuItem: '',
                currentMenuId: 0,
            },
        },
        currentId: 0,
        currentBox: 'element_4',
    },
    globalSettingsPageId: '5ed6478aec5aa62ae89844a1',
    globalSettingsPageObject: {
        draft: { structure: [], values: {}, connectedResources: [] },
        present: {},
        future: [],
        past: [],
        __v: 0,
        _id: '5ed6478aec5aa62ae89844a1',
    },
    globalSettingsPageDraft: {
        structure: [],
        values: {},
        connectedResources: [],
    },
    globalSettingsTemplateId: '5ed6478aec5aa62ae89844a2',
    globalSettingsTemplateDraft: {
        currentId: 3,
        structure: [{ id: 'element_02', path: [], tag: 'CMS variables' }],
        values: { element_02: { properties: {}, style: '' } },
        connectedResources: [],
    },
    pageTemplateName: 'TestTemp',
    pageTemplateId: '5ed6af242c0e9615bc6e15ad',
    pageTemplateItem: {
        id: '5ed6af242c0e9615bc6e15ad',
        path: [],
        name: 'TestTemp',
        published: true,
        connectedResources: [
            { name: 'TestPlugVar', type: 'plugin' },
            { name: 'TestPlug', type: 'plugin' },
        ],
    },
    pageTemplateObject: {
        draft: {
            currentId: 5,
            structure: [
                {
                    id: 'element_02',
                    path: [],
                    tag: 'CMS variables',
                    itemPath: [],
                    expanded: true,
                },
                {
                    id: 'element_4',
                    tag: 'TestPlugVar',
                    isPropagatingItem: false,
                    textMode: 'text',
                    text: false,
                    isChildren: false,
                    isCMSVariable: true,
                    isElementFromCMSVariable: false,
                    itemPath: ['element_02'],
                    path: ['element_02'],
                },
                {
                    id: 'element_01',
                    path: [],
                    tag: 'html',
                    itemPath: [],
                    expanded: true,
                },
                {
                    id: 'element_0',
                    path: ['element_01'],
                    tag: 'head',
                    itemPath: ['element_01'],
                },
                {
                    id: 'element_1',
                    path: ['element_01'],
                    tag: 'body',
                    itemPath: ['element_01'],
                    expanded: true,
                },
                {
                    id: 'element_2',
                    path: ['element_01', 'element_1'],
                    tag: 'div',
                    itemPath: ['element_01', 'element_1'],
                },
                {
                    id: 'element_3',
                    tag: 'TestPlug',
                    isPropagatingItem: false,
                    textMode: 'text',
                    text: false,
                    isChildren: false,
                    isCMSVariable: false,
                    isElementFromCMSVariable: false,
                    itemPath: ['element_01', 'element_1'],
                    path: ['element_01', 'element_1'],
                },
            ],
            values: {
                element_02: { properties: {}, style: '' },
                element_01: { properties: {}, style: '' },
                element_0: { properties: {}, style: '' },
                element_1: { properties: {}, style: '' },
                element_2: {
                    properties: {},
                    style:
                        'height: 100px;width: 100px;left: 200px;top: 100px;z-index: 0;background: rgba(100, 0, 80);',
                },
                element_3: {
                    textContent: '',
                    properties: { items: 'testPlugVar' },
                    propertiesString: '{"items":"testPlugVar"}',
                    CMSVariableType: 'text',
                    CMSVariableSystemName: 'newCmsVariable',
                    CMSVariableDescription: 'New CMS variable description',
                    CMSVariableDefaultValue: 'New CMS variable default value',
                    cursorPosition: { row: 1, column: 23 },
                },
                element_4: {
                    textContent: '',
                    properties: {},
                    propertiesString: '',
                    CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                    CMSVariableSystemName: 'testPlugVar',
                    CMSVariableDescription: 'New CMS variable description',
                    CMSVariableDefaultValue: 'New CMS variable default value',
                },
            },
            connectedResources: [
                { name: 'TestPlugVar', type: 'plugin' },
                { name: 'TestPlug', type: 'plugin' },
            ],
            currentBox: 'element_3',
        },
        present: {},
        future: [],
        past: [],
        __v: 2,
        _id: '5ed6af242c0e9615bc6e15ad',
    },
    pageTemplateDraft: {
        currentId: 5,
        structure: [
            {
                id: 'element_02',
                path: [],
                tag: 'CMS variables',
                itemPath: [],
                expanded: true,
            },
            {
                id: 'element_4',
                tag: 'TestPlugVar',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: true,
                isElementFromCMSVariable: false,
                itemPath: ['element_02'],
                path: ['element_02'],
            },
            {
                id: 'element_01',
                path: [],
                tag: 'html',
                itemPath: [],
                expanded: true,
            },
            {
                id: 'element_0',
                path: ['element_01'],
                tag: 'head',
                itemPath: ['element_01'],
            },
            {
                id: 'element_1',
                path: ['element_01'],
                tag: 'body',
                itemPath: ['element_01'],
                expanded: true,
            },
            {
                id: 'element_2',
                path: ['element_01', 'element_1'],
                tag: 'div',
                itemPath: ['element_01', 'element_1'],
            },
            {
                id: 'element_3',
                tag: 'TestPlug',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                itemPath: ['element_01', 'element_1'],
                path: ['element_01', 'element_1'],
            },
        ],
        values: {
            element_02: { properties: {}, style: '' },
            element_01: { properties: {}, style: '' },
            element_0: { properties: {}, style: '' },
            element_1: { properties: {}, style: '' },
            element_2: {
                properties: {},
                style:
                    'height: 100px;width: 100px;left: 200px;top: 100px;z-index: 0;background: rgba(100, 0, 80);',
            },
            element_3: {
                textContent: '',
                properties: { items: 'testPlugVar' },
                propertiesString: '{"items":"testPlugVar"}',
                CMSVariableType: 'text',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                cursorPosition: { row: 1, column: 23 },
            },
            element_4: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                CMSVariableSystemName: 'testPlugVar',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
            },
        },
        connectedResources: [
            { name: 'TestPlugVar', type: 'plugin' },
            { name: 'TestPlug', type: 'plugin' },
        ],
        currentBox: 'element_3',
    },
    pageTemplateFSBName: 'TestTemp',
    pageTemplateFSBId: '5ed6af242c0e9615bc6e15ad',
    pageTemplateFSBItem: {
        id: '5ed6af242c0e9615bc6e15ad',
        path: [],
        name: 'TestTemp',
        published: true,
        connectedResources: [
            { name: 'TestPlugVar', type: 'plugin' },
            { name: 'TestPlug', type: 'plugin' },
        ],
    },
    pageTemplateFSBObject: {
        draft: {
            currentId: 5,
            structure: [
                {
                    id: 'element_02',
                    path: [],
                    tag: 'CMS variables',
                    itemPath: [],
                    expanded: true,
                },
                {
                    id: 'element_4',
                    tag: 'TestPlugVar',
                    isPropagatingItem: false,
                    textMode: 'text',
                    text: false,
                    isChildren: false,
                    isCMSVariable: true,
                    isElementFromCMSVariable: false,
                    itemPath: ['element_02'],
                    path: ['element_02'],
                },
                {
                    id: 'element_01',
                    path: [],
                    tag: 'html',
                    itemPath: [],
                    expanded: true,
                },
                {
                    id: 'element_0',
                    path: ['element_01'],
                    tag: 'head',
                    itemPath: ['element_01'],
                },
                {
                    id: 'element_1',
                    path: ['element_01'],
                    tag: 'body',
                    itemPath: ['element_01'],
                    expanded: true,
                },
                {
                    id: 'element_2',
                    path: ['element_01', 'element_1'],
                    tag: 'div',
                    itemPath: ['element_01', 'element_1'],
                },
                {
                    id: 'element_3',
                    tag: 'TestPlug',
                    isPropagatingItem: false,
                    textMode: 'text',
                    text: false,
                    isChildren: false,
                    isCMSVariable: false,
                    isElementFromCMSVariable: false,
                    itemPath: ['element_01', 'element_1'],
                    path: ['element_01', 'element_1'],
                },
            ],
            values: {
                element_02: { properties: {}, style: '' },
                element_01: { properties: {}, style: '' },
                element_0: { properties: {}, style: '' },
                element_1: { properties: {}, style: '' },
                element_2: {
                    properties: {},
                    style:
                        'height: 100px;width: 100px;left: 200px;top: 100px;z-index: 0;background: rgba(100, 0, 80);',
                },
                element_3: {
                    textContent: '',
                    properties: { items: 'testPlugVar' },
                    propertiesString: '{"items":"testPlugVar"}',
                    CMSVariableType: 'text',
                    CMSVariableSystemName: 'newCmsVariable',
                    CMSVariableDescription: 'New CMS variable description',
                    CMSVariableDefaultValue: 'New CMS variable default value',
                    cursorPosition: { row: 1, column: 23 },
                },
                element_4: {
                    textContent: '',
                    properties: {},
                    propertiesString: '',
                    CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                    CMSVariableSystemName: 'testPlugVar',
                    CMSVariableDescription: 'New CMS variable description',
                    CMSVariableDefaultValue: 'New CMS variable default value',
                },
            },
            connectedResources: [
                { name: 'TestPlugVar', type: 'plugin' },
                { name: 'TestPlug', type: 'plugin' },
            ],
            currentBox: 'element_3',
        },
        present: {},
        future: [],
        past: [],
        __v: 2,
        _id: '5ed6af242c0e9615bc6e15ad',
    },
    pageTemplateFSBDraft: {
        currentId: 5,
        structure: [
            {
                id: 'element_02',
                path: [],
                tag: 'CMS variables',
                itemPath: [],
                expanded: true,
            },
            {
                id: 'element_4',
                tag: 'TestPlugVar',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: true,
                isElementFromCMSVariable: false,
                itemPath: ['element_02'],
                path: ['element_02'],
            },
            {
                id: 'element_01',
                path: [],
                tag: 'html',
                itemPath: [],
                expanded: true,
            },
            {
                id: 'element_0',
                path: ['element_01'],
                tag: 'head',
                itemPath: ['element_01'],
            },
            {
                id: 'element_1',
                path: ['element_01'],
                tag: 'body',
                itemPath: ['element_01'],
                expanded: true,
            },
            {
                id: 'element_2',
                path: ['element_01', 'element_1'],
                tag: 'div',
                itemPath: ['element_01', 'element_1'],
            },
            {
                id: 'element_3',
                tag: 'TestPlug',
                isPropagatingItem: false,
                textMode: 'text',
                text: false,
                isChildren: false,
                isCMSVariable: false,
                isElementFromCMSVariable: false,
                itemPath: ['element_01', 'element_1'],
                path: ['element_01', 'element_1'],
            },
        ],
        values: {
            element_02: { properties: {}, style: '' },
            element_01: { properties: {}, style: '' },
            element_0: { properties: {}, style: '' },
            element_1: { properties: {}, style: '' },
            element_2: {
                properties: {},
                style:
                    'height: 100px;width: 100px;left: 200px;top: 100px;z-index: 0;background: rgba(100, 0, 80);',
            },
            element_3: {
                textContent: '',
                properties: { items: 'testPlugVar' },
                propertiesString: '{"items":"testPlugVar"}',
                CMSVariableType: 'text',
                CMSVariableSystemName: 'newCmsVariable',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
                cursorPosition: { row: 1, column: 23 },
            },
            element_4: {
                textContent: '',
                properties: {},
                propertiesString: '',
                CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                CMSVariableSystemName: 'testPlugVar',
                CMSVariableDescription: 'New CMS variable description',
                CMSVariableDefaultValue: 'New CMS variable default value',
            },
        },
        connectedResources: [
            { name: 'TestPlugVar', type: 'plugin' },
            { name: 'TestPlug', type: 'plugin' },
        ],
        currentBox: 'element_3',
    },
    resourcesObjects: {
        '5ed6478aec5aa62ae898449f': {
            websites: [{ id: '5ed6478aec5aa62ae89844a0' }],
            settings: {
                websites: {
                    '5ed6478aec5aa62ae89844a0': {
                        currentPageFSBId: '5ed6af842c0e9615bc6e15ae',
                        currentPageId: '5ed6af842c0e9615bc6e15ae',
                    },
                },
                currentWebsite: '5ed6478aec5aa62ae89844a0',
            },
            logoutAllDate: 1591100722138,
            _id: '5ed6478aec5aa62ae898449f',
            userid: '7085000',
            platformId: 'github',
            accountInfo: {
                displayName: null,
                photos: [
                    {
                        value:
                            'https://avatars0.githubusercontent.com/u/7085000?v=4',
                    },
                ],
            },
            __v: 0,
        },
        '5ed6478aec5aa62ae89844a0': {
            sharing: [
                {
                    userId: '5ed6478aec5aa62ae898449f',
                    rights: ['owner', 'admin', 'developer', 'content'],
                    accountInfo: {
                        displayName: null,
                        photos: [
                            {
                                value:
                                    'https://avatars0.githubusercontent.com/u/7085000?v=4',
                            },
                        ],
                    },
                },
            ],
            filesStructure: [],
            pagesStructure: [
                {
                    id: '5ed6478aec5aa62ae89844a1',
                    name: 'Global website settings',
                    url: '__general__settings__',
                    hidden: true,
                    path: [],
                    published: true,
                    generalSettings: true,
                    template: 'Global website settings',
                    relUrl: '/__general__settings__',
                },
                {
                    id: '5ed6af842c0e9615bc6e15ae',
                    path: [],
                    name: 'New page',
                    url: 'new-page',
                    hidden: true,
                    published: true,
                    homepage: false,
                    relUrl: '/new-page',
                    template: 'TestTemp',
                    connectedResources: null,
                },
            ],
            pluginsStructure: [
                {
                    id: '5ed6aebb2c0e9615bc6e15ac',
                    path: [],
                    name: 'TestPlug',
                    published: true,
                    propagating: true,
                    connectedResources: [
                        { name: 'TestVar1', type: 'plugin' },
                        { name: 'TestVar2', type: 'plugin' },
                        { name: 'TestVar3', type: 'plugin' },
                    ],
                },
            ],
            templatesStructure: [
                {
                    id: '5ed6478aec5aa62ae89844a2',
                    name: 'Global website settings',
                    url: '__general__settings__',
                    hidden: true,
                    path: [],
                    published: true,
                    generalSettings: true,
                },
                {
                    id: '5ed6af242c0e9615bc6e15ad',
                    path: [],
                    name: 'TestTemp',
                    published: true,
                    connectedResources: [
                        { name: 'TestPlugVar', type: 'plugin' },
                        { name: 'TestPlug', type: 'plugin' },
                    ],
                },
            ],
            _id: '5ed6478aec5aa62ae89844a0',
            name: 'New website',
            domain: 'new-website-3',
            user: '5ed6478aec5aa62ae898449f',
            storage: 0,
            __v: 13,
            __patch__: {
                sharing: {
                    '0': [
                        {
                            userId: '5ed6478aec5aa62ae898449f',
                            rights: ['owner', 'admin', 'developer', 'content'],
                            accountInfo: {
                                displayName: null,
                                photos: [
                                    {
                                        value:
                                            'https://avatars0.githubusercontent.com/u/7085000?v=4',
                                    },
                                ],
                            },
                        },
                    ],
                    _t: 'a',
                    _0: [
                        {
                            userId: '5ed6478aec5aa62ae898449f',
                            rights: ['owner', 'admin', 'developer', 'content'],
                            accountInfo: {
                                displayName: null,
                                photos: [
                                    {
                                        value:
                                            'https://avatars0.githubusercontent.com/u/7085000?v=4',
                                    },
                                ],
                            },
                        },
                        0,
                        0,
                    ],
                },
                pagesStructure: { '1': { published: [false, true] }, _t: 'a' },
                pluginsStructure: {
                    '0': {
                        connectedResources: {
                            '0': [{ name: 'TestVar1', type: 'plugin' }],
                            '1': [{ name: 'TestVar2', type: 'plugin' }],
                            '2': [{ name: 'TestVar3', type: 'plugin' }],
                            _t: 'a',
                            _0: [{ name: 'TestVar1', type: 'plugin' }, 0, 0],
                            _1: [{ name: 'TestVar2', type: 'plugin' }, 0, 0],
                            _2: [{ name: 'TestVar3', type: 'plugin' }, 0, 0],
                        },
                    },
                    _t: 'a',
                },
                templatesStructure: {
                    '1': {
                        connectedResources: {
                            '0': [{ name: 'TestPlugVar', type: 'plugin' }],
                            '1': [{ name: 'TestPlug', type: 'plugin' }],
                            _t: 'a',
                            _0: [{ name: 'TestPlugVar', type: 'plugin' }, 0, 0],
                            _1: [{ name: 'TestPlug', type: 'plugin' }, 0, 0],
                        },
                    },
                    _t: 'a',
                },
            },
        },
        '5ed6af842c0e9615bc6e15ae': {
            draft: {
                structure: [
                    {
                        id: 'element_4',
                        tag: 'TestPlugVar',
                        isPropagatingItem: false,
                        textMode: 'text',
                        text: false,
                        isChildren: false,
                        isCMSVariable: false,
                        isElementFromCMSVariable: false,
                        path: [],
                        CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                    },
                ],
                values: {
                    element_4: {
                        textContent: '',
                        properties: {},
                        propertiesString: '',
                        CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                        CMSVariableSystemName: 'testPlugVar',
                        CMSVariableDescription: 'New CMS variable description',
                        CMSVariableDefaultValue:
                            'New CMS variable default value',
                        value: '',
                        menuItems: [],
                        currentMenuItem: '',
                        currentMenuId: 0,
                    },
                },
                currentId: 0,
            },
            present: {
                structure: [
                    {
                        id: 'element_4',
                        tag: 'TestPlugVar',
                        isPropagatingItem: false,
                        textMode: 'text',
                        text: false,
                        isChildren: false,
                        isCMSVariable: false,
                        isElementFromCMSVariable: false,
                        CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                        itemPath: [],
                        path: [],
                    },
                ],
                values: {
                    element_4: {
                        textContent: '',
                        properties: {},
                        propertiesString: '',
                        CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                        CMSVariableSystemName: 'testPlugVar',
                        CMSVariableDescription: 'New CMS variable description',
                        CMSVariableDefaultValue:
                            'New CMS variable default value',
                        value: '',
                        menuItems: [],
                        currentMenuItem: '',
                        currentMenuId: 0,
                    },
                },
                currentId: 0,
                currentBox: 'element_4',
            },
            future: [],
            past: [],
            __v: 2,
            _id: '5ed6af842c0e9615bc6e15ae',
        },
        '5ed6478aec5aa62ae89844a2': {
            draft: {
                currentId: 3,
                structure: [
                    { id: 'element_02', path: [], tag: 'CMS variables' },
                ],
                values: { element_02: { properties: {}, style: '' } },
                connectedResources: [],
            },
            present: {},
            future: [],
            past: [],
            __v: 0,
            _id: '5ed6478aec5aa62ae89844a2',
        },
        '5ed6478aec5aa62ae89844a1': {
            draft: { structure: [], values: {}, connectedResources: [] },
            present: {},
            future: [],
            past: [],
            __v: 0,
            _id: '5ed6478aec5aa62ae89844a1',
        },
        '5ed6af242c0e9615bc6e15ad': {
            draft: {
                currentId: 5,
                structure: [
                    {
                        id: 'element_02',
                        path: [],
                        tag: 'CMS variables',
                        itemPath: [],
                        expanded: true,
                    },
                    {
                        id: 'element_4',
                        tag: 'TestPlugVar',
                        isPropagatingItem: false,
                        textMode: 'text',
                        text: false,
                        isChildren: false,
                        isCMSVariable: true,
                        isElementFromCMSVariable: false,
                        itemPath: ['element_02'],
                        path: ['element_02'],
                    },
                    {
                        id: 'element_01',
                        path: [],
                        tag: 'html',
                        itemPath: [],
                        expanded: true,
                    },
                    {
                        id: 'element_0',
                        path: ['element_01'],
                        tag: 'head',
                        itemPath: ['element_01'],
                    },
                    {
                        id: 'element_1',
                        path: ['element_01'],
                        tag: 'body',
                        itemPath: ['element_01'],
                        expanded: true,
                    },
                    {
                        id: 'element_2',
                        path: ['element_01', 'element_1'],
                        tag: 'div',
                        itemPath: ['element_01', 'element_1'],
                    },
                    {
                        id: 'element_3',
                        tag: 'TestPlug',
                        isPropagatingItem: false,
                        textMode: 'text',
                        text: false,
                        isChildren: false,
                        isCMSVariable: false,
                        isElementFromCMSVariable: false,
                        itemPath: ['element_01', 'element_1'],
                        path: ['element_01', 'element_1'],
                    },
                ],
                values: {
                    element_02: { properties: {}, style: '' },
                    element_01: { properties: {}, style: '' },
                    element_0: { properties: {}, style: '' },
                    element_1: { properties: {}, style: '' },
                    element_2: {
                        properties: {},
                        style:
                            'height: 100px;width: 100px;left: 200px;top: 100px;z-index: 0;background: rgba(100, 0, 80);',
                    },
                    element_3: {
                        textContent: '',
                        properties: { items: 'testPlugVar' },
                        propertiesString: '{"items":"testPlugVar"}',
                        CMSVariableType: 'text',
                        CMSVariableSystemName: 'newCmsVariable',
                        CMSVariableDescription: 'New CMS variable description',
                        CMSVariableDefaultValue:
                            'New CMS variable default value',
                        cursorPosition: { row: 1, column: 23 },
                    },
                    element_4: {
                        textContent: '',
                        properties: {},
                        propertiesString: '',
                        CMSVariableType: 'propagating_5ed6aebb2c0e9615bc6e15ac',
                        CMSVariableSystemName: 'testPlugVar',
                        CMSVariableDescription: 'New CMS variable description',
                        CMSVariableDefaultValue:
                            'New CMS variable default value',
                    },
                },
                connectedResources: [
                    { name: 'TestPlugVar', type: 'plugin' },
                    { name: 'TestPlug', type: 'plugin' },
                ],
                currentBox: 'element_3',
            },
            present: {},
            future: [],
            past: [],
            __v: 2,
            _id: '5ed6af242c0e9615bc6e15ad',
        },
        '5ed6aebb2c0e9615bc6e15ac': {
            draft: {
                currentId: 7,
                structure: [
                    {
                        id: 'element_02',
                        text: false,
                        isChildren: false,
                        forChildren: false,
                        tag: 'CMS variables',
                        expanded: true,
                        itemPath: [],
                        path: [],
                    },
                    {
                        id: 'element_5',
                        tag: 'TestVar1',
                        isPropagatingItem: false,
                        textMode: 'text',
                        text: false,
                        isChildren: false,
                        isCMSVariable: true,
                        isElementFromCMSVariable: false,
                        itemPath: ['element_02'],
                        path: ['element_02'],
                    },
                    {
                        id: 'element_6',
                        tag: 'TestVar2',
                        isPropagatingItem: false,
                        textMode: 'text',
                        text: false,
                        isChildren: false,
                        isCMSVariable: true,
                        isElementFromCMSVariable: false,
                        itemPath: ['element_02'],
                        path: ['element_02'],
                    },
                    {
                        id: 'element_4',
                        tag: 'TestVar3',
                        isPropagatingItem: false,
                        textMode: 'text',
                        text: false,
                        isChildren: false,
                        isCMSVariable: true,
                        isElementFromCMSVariable: false,
                        itemPath: ['element_02'],
                        path: ['element_02'],
                    },
                    {
                        id: 'element_0',
                        path: [],
                        tag: 'Main element',
                        itemPath: [],
                        expanded: true,
                    },
                    {
                        id: 'element_1',
                        tag: 'div',
                        isPropagatingItem: false,
                        textMode: 'text',
                        text: false,
                        isChildren: false,
                        isCMSVariable: false,
                        isElementFromCMSVariable: false,
                        itemPath: ['element_0'],
                        path: ['element_0'],
                    },
                    {
                        id: 'element_2',
                        tag: 'div',
                        isPropagatingItem: false,
                        textMode: 'text',
                        text: false,
                        isChildren: false,
                        isCMSVariable: false,
                        isElementFromCMSVariable: false,
                        itemPath: ['element_0'],
                        path: ['element_0'],
                    },
                    {
                        id: 'element_3',
                        tag: 'div',
                        isPropagatingItem: false,
                        textMode: 'text',
                        text: false,
                        isChildren: false,
                        isCMSVariable: false,
                        isElementFromCMSVariable: false,
                        itemPath: ['element_0'],
                        path: ['element_0'],
                    },
                ],
                values: {
                    element_0: { properties: {} },
                    element_1: {
                        textContent: '',
                        properties: {},
                        propertiesString: '',
                        CMSVariableType: 'text',
                        CMSVariableSystemName: 'newCmsVariable',
                        CMSVariableDescription: 'New CMS variable description',
                        CMSVariableDefaultValue:
                            'New CMS variable default value',
                    },
                    element_2: {
                        textContent: '',
                        properties: {},
                        propertiesString: '',
                        CMSVariableType: 'text',
                        CMSVariableSystemName: 'newCmsVariable',
                        CMSVariableDescription: 'New CMS variable description',
                        CMSVariableDefaultValue:
                            'New CMS variable default value',
                    },
                    element_3: {
                        textContent: '',
                        properties: {},
                        propertiesString: '',
                        CMSVariableType: 'text',
                        CMSVariableSystemName: 'newCmsVariable',
                        CMSVariableDescription: 'New CMS variable description',
                        CMSVariableDefaultValue:
                            'New CMS variable default value',
                    },
                    element_4: {
                        textContent: '',
                        properties: {},
                        propertiesString: '',
                        CMSVariableType: 'text',
                        CMSVariableSystemName: 'testVar3',
                        CMSVariableDescription: 'New CMS variable description',
                        CMSVariableDefaultValue:
                            'New CMS variable default value',
                    },
                    element_5: {
                        textContent: '',
                        properties: {},
                        propertiesString: '',
                        CMSVariableType: 'text',
                        CMSVariableSystemName: 'testVar1',
                        CMSVariableDescription: 'New CMS variable description',
                        CMSVariableDefaultValue:
                            'New CMS variable default value',
                    },
                    element_6: {
                        textContent: '',
                        properties: {},
                        propertiesString: '',
                        CMSVariableType: 'text',
                        CMSVariableSystemName: 'testVar2',
                        CMSVariableDescription: 'New CMS variable description',
                        CMSVariableDefaultValue:
                            'New CMS variable default value',
                    },
                },
                connectedResources: [
                    { name: 'TestVar1', type: 'plugin' },
                    { name: 'TestVar2', type: 'plugin' },
                    { name: 'TestVar3', type: 'plugin' },
                ],
                currentBox: 'element_5',
            },
            present: {},
            future: [],
            past: [],
            __v: 2,
            _id: '5ed6aebb2c0e9615bc6e15ac',
        },
    },
    userId: '5ed6478aec5aa62ae898449f',
    nextFileId: 0,
    prod: false,
}
